name: Hello_Flutter
description: Learning Flutter for real.
version: 1.0.0+1
#created: 10 Apr 2020

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  assets_audio_player: 1.3.8

dev_dependencies:
  flutter_launcher_icons: "^0.8.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "app_icon"
  ios: "app_icon"
  image_path: "images/flutter_cropped.jpg"

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/dice/
    - assets/xylo/

  fonts:
    - family: Courgette
      fonts:
        - asset: fonts/Courgette-Regular.ttf

    - family: CourierPrime
      fonts:
        - asset: fonts/CourierPrime-Regular.ttf
